Add a config for using new optimized subsetting algorithm
VEuPathDB/EdaCommon pull request #18
Opened 2022-08-10 17:57 UTC by dmgaldi

## Overview
Add an optional report config for using binary files.

## Testing
Tested in docker environment

2022-08-10 18:07 UTC, ryanrdoherty requested changes

2022-08-10 18:07 UTC, ryanrdoherty commented on schema/url/query.raml
> +      useBinaryFiles?: boolean
If Steve was reviewing, he would say we should use an enum here, and I think I agree this time because if not using binary files, then what?  Not clear to the caller.  So maybe `dataSourceType: [ 'database', 'file' ]

2022-08-10 20:33 UTC, dmgaldi commented on schema/url/query.raml
> +      useBinaryFiles?: boolean
Yeah, fair point. Updated in newest commit

2022-08-11 01:25 UTC, ryanrdoherty approved these changes

2022-08-11 15:42 UTC, merged