study specific vocabs in SAM floaters
VEuPathDB/EdaCommon pull request #33
Opened 2023-08-21 18:34 UTC by d-callan

2023-08-22 13:35 UTC, dmgaldi commented on src/main/java/org/veupathdb/service/eda/common/client/EdaSubsettingClient.java
> +    }
Since this endpoint is tabular instead of JSON, we can change from `APPLICATION_JSON` to `MimeTypes.TEXT_TABULAR`.

We also can't deserialize the tabular response, we can just return the `ResponseFuture` directly, similar to the other tabular endpoints.

2023-08-22 13:47 UTC, d-callan commented on src/main/java/org/veupathdb/service/eda/common/client/EdaSubsettingClient.java
> +    }
thanks. tbh i didnt remember and hadnt looked again yet at the api for this endpoint.

2023-08-22 13:49 UTC, d-callan commented
@dmgaldi some specific questions i have:
1. does it make sense to add the new annotations to VariableDef? thatd be required to validate the variableSpec i think? or do we think theres a better way to do this?
2. whats this ss-internal thing im seeing? should this have been an internal endpoint?
3. assuming we add the new annotations to VariableDef and ReferenceMetadata, what else needs doing for me to be able to use them here and in the data service?

2023-08-22 14:02 UTC, dmgaldi commented
> @dmgaldi some specific questions i have:
> 
>     1. does it make sense to add the new annotations to VariableDef? thatd be required to validate the variableSpec i think? or do we think theres a better way to do this?
 * Yeah, I can add the new annotations. I was just holding off until I can actually see them in the database to make sure I'm parsing them out correctly. I can make a note to add the validation in here once I get the annotation wired up.
> 
>     2. whats this ss-internal thing im seeing? should this have been an internal endpoint?
> 
* the difference between ss-internal and subsetting is that ss-internal is only available on the internal network and doesn't check for dataset access permissions. I'm thinking maybe I should move the endpoint to be a child of ss-internal, but for now it's not
>     3. assuming we add the new annotations to VariableDef and ReferenceMetadata, what else needs doing for me to be able to use them here and in the data service?
* I think that should be all that's needed. We might want some utility if we don't have one to help make the response available in R.

2023-08-29 20:45 UTC, dmgaldi requested changes
Big picture looks good, just a few small comments

2023-08-29 20:45 UTC, dmgaldi commented on src/main/java/org/veupathdb/service/eda/common/client/EdaSubsettingClient.java
> +import com.oracle.truffle.api.impl.TruffleLocator.Response;
Looks like an unused import

2023-08-29 20:45 UTC, dmgaldi commented on src/main/java/org/veupathdb/service/eda/common/plugin/util/PluginUtil.java
> +  public String getHasStudyDependentVocabulary(VariableSpec var) {
Should these return boolean instead of string? As is it looks like these will return stringified booleans which will be harder to use for consumers.

2023-08-29 20:45 UTC, dmgaldi commented on src/main/java/org/veupathdb/service/eda/common/plugin/util/PluginUtil.java
> +    String dotNotatedIdColumnsString = "c(";
This is an unintuitive java thing, but strings are immutable so this function could end up being pretty memory intensive. We can use a StringBuilder here to create the string in-place.

2023-08-31 19:42 UTC, dmgaldi approved these changes

2023-09-06 16:37 UTC, d-callan commented on src/main/java/org/veupathdb/service/eda/common/client/EdaSubsettingClient.java
> +    String url = getUrl("/studies/" + metadata.getStudyId() + "/entities" + varSpec.getEntityId() + "/variables/" + varSpec.getVariableId() + "/root-vocab");
@dmgaldi im not sure we remembered variable collections here..

2023-10-13 18:04 UTC, merged